// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'main.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBilI-ZGsNXxKfEbKpWAIv-IpwkaJ0L48',
    appId: '1:928133064448:android:bea88c5de1df9402b3f5e5',
    messagingSenderId: '928133064448',
    projectId: 'notif-test-9915e',
    storageBucket: 'notif-test-9915e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkepjSZKxbOphnZfbigM6fOWXbjMDzf6c',
    appId: '1:928133064448:ios:3a3b55174dcee3cdb3f5e5',
    messagingSenderId: '928133064448',
    projectId: 'notif-test-9915e',
    storageBucket: 'notif-test-9915e.appspot.com',
    androidClientId: '928133064448-8tjuadrtd635bkjo8a756fsuea5td13g.apps.googleusercontent.com',
    iosClientId: '928133064448-cihut5enoa5rk9ff63tr81pbgbkiro2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.signalrClient',
  );
}
